### PR TITLE
Implemented saving the project and add it to the data.json file

### PR DESCRIPTION
**Pull request by kavinda1995**
- Reformatting and linting some old codes to the standard

- Created **FormButtonElement** as to be used in forms to call functions etc.

- Saving new projects as it adds on "Add New Project"

- Save new project to the data.js file

### CODE REVIEW

**Comment by kavinda1995** [comment]
I have completed save project to the json file.

**Comment by kavinda1995** [comment]
Code quality fix done

**Comment by kavinda1995** [comment]
Fixed Quality error Version 02

**Comment by kavinda1995** [comment]
Toast added and API error handling done in a better way

**Review by PMArtz92 — APPROVED** [review]

**Pull request merged**
